from   ubuntu

RUN apt-get update
RUN apt-get install -y git ansible emacs software-properties-common
RUN apt-get install -y yaml-mode yamllint
RUN apt-add-repository ppa:ansible/ansible
RUN apt-get update
RUN apt-get install -y ansible

